language: ruby
cache:
  - bundler
dist: trusty
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler
script: "bundle exec thor spec"
matrix:
  include:
  - rvm: 2.2.5
  - rvm: 2.3.1
  - rvm: ruby-head
