#!/usr/bin/env bash

if
  [[ -s "/Users/dg091242/.rvm/gems/ruby-2.4.1/environment" ]]
then
  source "/Users/dg091242/.rvm/gems/ruby-2.4.1/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/dg091242/.rvm/gems/ruby-2.4.1/environment'" >&2
  exit 1
fi
