sudo: false
language: ruby
cache: bundler
dist: precise
branches:
  only:
    - master
addons:
  apt:
    packages:
    - libarchive12
    - libarchive-dev
matrix:
  include:
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: ruby-head
script: bundle exec rake spec
