sudo: false
language: ruby
addons:
  apt:
    packages:
      - chef
      - git
      - graphviz
      - libarchive12
      - libarchive-dev
      - libgecode-dev
    sources:
      - chef-stable-precise
cache:
  - apt
  - bundler
bundler_args: --without development
dist: precise
branches:
  only:
    - master
script: "bundle exec thor spec:all"
before_install:
  - gem update --system
  - gem install bundler
matrix:
  include:
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: ruby-head
    # Test against master of berkshelf
#    - rvm: 2.2.5
#      gemfile: berkshelf/Gemfile
#      before_install:
#        - gem update --system
#        - gem install bundler
#        - git clone --depth 1 https://github.com/berkshelf/berkshelf
#        - cd berkshelf
#        - echo "gem 'ridley', :path => '..'" >> Gemfile
#      install: bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
#      env:
#      script: bundle exec thor spec:ci
