#!/usr/bin/env bash

if
  [[ -s "/Users/dg091242/.rvm/gems/ruby-2.3.3@global/environment" ]]
then
  source "/Users/dg091242/.rvm/gems/ruby-2.3.3@global/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/dg091242/.rvm/gems/ruby-2.3.3@global/environment'" >&2
  exit 1
fi
